if: tag IS blank
sudo: required
services:
- docker
env:
  global:
  - REGISTRY_USER=slashe
  - secure: eMeByy13+U/I0PGiyma1wcjO9+xtZZ56onLQs/qyWjB6p/n6JpHfgPhyDqjjSR1V4+Npja21rpWDqEw+d0ONKypHV9AE4VT+3wSnUKJEkyzQ9akEVg51A9+oKeA83UcZn0GePQbgyJbzG8+c77sNSimq7DvSBUIGpOhV+XeNUrsqQeXAaGCpeZ4dqmHV46dDztUIveaw3OvgICOyDMHrEKT0APFPq2aMA9T01ulTMh2NvfVEBS1R5VOUw6BKdBuQRETWH8cUKSzT2tr1ieWI7vuPX+00x8tRA9tC83DgIwsyzgp0J9FLCLxW9JUwHqu+IRhXbsLKY6P7TQSy2KbETpLtDyDvKGKDT4d+qgpeAEgp0asxjWAZoNhcCmhfl6KZSBq6UfJwY9TxIbD9kcB2+z0NfJy8Tn5aD+FdZI+g6JklQuUGxFE3KoySGv5Ruq7OodhFwqQo+nKvVspRiGCRPphEUWEKZTkcA0j0X/CeShpiUg/Je1wNhdLtUH4eqUOegt1ihgqAeakRNlKQe1b+y+MdZevLFyU9KDhPIWEza4MKG5p27h63naDN4KlZsak54ucR3uspxI1KEMQ3mMLDy8MHnf5tgN/dsmKeC2GVLclVaE+hXLApokoBaYyOTk3mlbMF17jyy43/HJunWupKBHmdZuuiuSFypcyduTfCiPw=
  - secure: SIubvUgxCy2Di/lLjLONQsyOzUEjAZE4Z3r3RlpCqLhBApNjY+2BPXLyvIlngnOIPRHszKqzwedhG8TItigUg1wOPA2o2BIlJliR2VRyJ20IoZ7Xlavpm4tdmo4QodR9MLLxWF93+QzVazkxP8yrVEf12o1i2ZjiRkEt8gubNFz2ld29QKSatjZVbE/CEZTXm9H8ZWOU/MxNfUOddF7ckp+KamLdvXwlVQjRD7oUB3akm02WjWl6+VZEOCVE4IED+wTdxp6PVi73Zn2STvk3N2zFxBNSG9F8Dtfd4+Mkq5eP1VQYOhzIphDk8Yn5eoeg9ViRfXmukwVvJvb9JV35OK2OzNe/dvYLOAfK2KmWganrXd8zKEn2/anaKfWu0wASBf4fESjOog/lInT0PU096VDWM3UXaLfGk4tCvk2ip0227hKL8cg3R/XCKr4LJo4wQFaq5QPdZI5WkvIJ4LEKkfqhhtE29BXGzoI13F2J77j1ZTrLQmym6LiUkqT+EmlpDfaOqSOSeO/8DVeBD/0h88E1/MZZ5nwxhS/y8sGXJaR7UYNZtGUWiKzHLPR/kWQmFCXoOQIB8zTCUTyqjXtNlfxthLm+vgk808dXQsjXX2aWfZdV893lsfAHjwYhEwcL5Mmx5NGBfOtgs/lJv1iAx5jFmi5qx+McNB6IEdx04WI=
script:
- git checkout master
- version=$(npm version patch)
- docker build --tag $REGISTRY_USER/docker-webapp:$version .
after_script:
- docker images
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
- docker push $REGISTRY_USER/docker-webapp:$version
after_success:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- git add .
- git tag $version -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER [skip
  ci]"
- git commit --amend -m "TravisCI build $version [skip ci]"
- git push --repo=https://$GITHUB_PERSONAL_ACCESS_TOKEN_FOR_TRAVIS@github.com/m-slashe/docker-webapp.git
  --all
- git push --repo=https://$GITHUB_PERSONAL_ACCESS_TOKEN_FOR_TRAVIS@github.com/m-slashe/docker-webapp.git
  --tags